n = input('Digite algo:')

print('é alfabetico ?',n.isalpha())
print('é um numero?',n.isnumeric())
print('é alfanumerico ?',n.isalnum())
print(n.isascii())
print(n.isdigit())
print(n.isdecimal())
print(n.isidentifier())
print('Esta em minusculas ?',n.islower())
print(n.isprintable())
print('So tem espacos? ',n.isspace())
print('Esta capitalizada ?',n.istitle())
print('Esta em maiuscula',n.isupper())
print(n.__init_subclass__())
